#!/bin/bash
#SCRIPT QUE REALIZA EL EMPAQUETADO DE FICHERO DE LOS ULTIMOS DIAS DESEADOS PARA QUE OCUPE MENOS ESPACIO EN DICHO LUGAR

#RUTA DONDE SE REALIZA EL CONTROL DEL EMPAQUETADO DE LOS FICHEROS
RUTA="/home/juanjose/script-empaquetado/INVENTARIO/PROCESADOS"

#NOMBRE Y TIPO DE FICHERO A FILTRAR PARA EL EMPAQUETADO
NAME_TYPE="*.csv"

#NUMERO DE DIAS
DAYSTART="7"
DAYEND="14"

#FECHA DE COPIA
DATE1=$(date --date='-7 day' +%d\%m\%Y)

#FECHA DE COMIENZO E LA COPIA
DATE2=$(date --date='-14 day' +%d\%m\%Y)

#TITULO
TITLE="empaquetado-semana-$DATE2-hasta-$DATE1.tar.gz"

find $RUTA -mtime +$DAYSTART -mtime -$DAYEND -iname "$NAME_TYPE" -exec tar -czvf $TITLE {} +
